version: "3.9"

services:
  db:
    image: postgres:13.1-alpine
    env_file: .env-db
  web:
    build: .
    depends_on:
    - db
    ports:
    - 5000:5000
    env_file: .env-web
    command: >
      sh -c "flask db upgrade && flask autocreatesuperuser && uvicorn app:fast_app --host=0.0.0.0 --port 5000"
